# Generated by Django 3.1.7 on 2021-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20210327_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='phone',
            field=models.CharField(max_length=9, verbose_name='Telefono'),
        ),
    ]
